/*
Author:              Rei Armenia & Matthew Harrison
Class:               CSI-340-01
Assignment:          Lab 2
Date Assigned:       September 19th
Due Date:            September 28th
 
Description:
Solo, Guitar Smash Solo. Code was generated by Rei Armenia & Matthew Harrison.
 
Certification of Authenticity:    
I certify that this is entirely my own work, except where I have been provided
code by the instructor, or given fully-documented references to the work of 
others. I understand the definition and consequences of plagiarism and 
acknowledge that the assessor of this assignment may, for the purpose of 
assessing this assignment:
    Reproduce this assignment and provide a copy to another member of academic
    staff; and/or Communicate a copy of this assignment to a plagiarism checking
    service (which may then retain a copy of this assignment on its database for 
    the purpose of future plagiarism checking) 
*/
package guitarhero.solo;

public class GuitarSmashSolo implements ISolo{

    @Override
    public void playSolo(String name){
        System.out.println(name + " smashed their Guitar.");
    }

}
