/*
Author:              Rei Armenia & Matthew Harrison
Class:               CSI-340-01
Assignment:          Lab 2
Date Assigned:       September 19th
Due Date:            September 28th
 
Description:
Game Character, Angus. Code was generated by Rei Armenia.
 
Certification of Authenticity:    
I certify that this is entirely my own work, except where I have been provided
code by the instructor, or given fully-documented references to the work of 
others. I understand the definition and consequences of plagiarism and 
acknowledge that the assessor of this assignment may, for the purpose of 
assessing this assignment:
    Reproduce this assignment and provide a copy to another member of academic
    staff; and/or Communicate a copy of this assignment to a plagiarism checking
    service (which may then retain a copy of this assignment on its database for 
    the purpose of future plagiarism checking) 
*/
package guitarhero.containers;

import guitarhero.guitar.IGuitar;
import guitarhero.solo.ISolo;

public class GameCharacterAngus extends GameCharacter {

    public GameCharacterAngus(String name, IGuitar guitar, ISolo solo){
        super(name, guitar, solo);
    }

    @Override
    public void display(){
        System.out.println(this.getName() + "looks like Angus Young!");
    }

}